CREATE TABLE IF NOT EXISTS tasks (
  task_id TEXT,
  label TEXT,
  language TEXT,
  upload_order INTEGER,
  package_count INTEGER,
  shard_count INTEGER,
  source_bundle TEXT,
  contains_shared_comparisons BOOLEAN,
  task_path TEXT,
  task_json JSON
);

CREATE TABLE IF NOT EXISTS shards (
  task_id TEXT,
  shard_id TEXT,
  label TEXT,
  language TEXT,
  upload_order INTEGER,
  package_count INTEGER,
  file_count INTEGER,
  total_bytes BIGINT,
  approx_token_estimate BIGINT,
  contains_comparisons BOOLEAN,
  depends_on_shared_comparisons BOOLEAN,
  content_digest_sha256 TEXT,
  shard_path TEXT,
  shard_json JSON
);

CREATE TABLE IF NOT EXISTS packages (
  task_id TEXT,
  shard_id TEXT,
  language TEXT,
  package TEXT,
  canonical_name TEXT,
  canonical_package_name TEXT,
  role_class TEXT,
  agent_safety_class TEXT,
  selection_priority TEXT,
  retrieval_priority TEXT,
  aliases JSON,
  query_aliases JSON,
  task_tags JSON,
  common_pairings JSON,
  top_functions_or_commands JSON,
  choose_when JSON,
  avoid_when JSON,
  not_for JSON,
  decision_traps JSON,
  neighbor_packages JSON,
  workflow_position JSON,
  manifest_path TEXT,
  summary_card_path TEXT,
  raw_doc_path TEXT,
  source_json JSON,
  version_json JSON,
  status_json JSON,
  content_presence_json JSON,
  manifest_json JSON
);

CREATE TABLE IF NOT EXISTS documents (
  doc_id TEXT,
  task_id TEXT,
  shard_id TEXT,
  language TEXT,
  package TEXT,
  canonical_package_name TEXT,
  source_kind TEXT,
  doc_type TEXT,
  chunk_type TEXT,
  importance_tier TEXT,
  title TEXT,
  function_or_command TEXT,
  section_title TEXT,
  retrieval_priority TEXT,
  role_class TEXT,
  agent_safety_class TEXT,
  keywords JSON,
  task_tags JSON,
  top_functions_or_commands JSON,
  path TEXT,
  open_doc_url TEXT,
  header_json JSON,
  body_text TEXT,
  full_text TEXT
);
